package net.puffish.skillsmod.arpg.stat;

import java.util.Locale;
import java.util.Optional;

public enum ArpgStat {
	MAXIMUM_LIFE,
	MAXIMUM_MANA,
	ARMOR,
	EVASION,
	WARD,
	ATTACK_SPEED,
	CAST_SPEED,
	PHYSICAL_DAMAGE,
	FIRE_DAMAGE,
	COLD_DAMAGE,
	LIGHTNING_DAMAGE,
	BLOOD_DAMAGE,
	HOLY_DAMAGE,
	ENDER_DAMAGE,
	SPELL_DAMAGE,
	ATTACK_DAMAGE,
	MELEE_DAMAGE,
	PROJECTILE_DAMAGE,
	CRITICAL_CHANCE,
	CRITICAL_MULTIPLIER,
	COOLDOWN_RECOVERY,
	BLOCK_CHANCE,
	SPELL_BLOCK,
	STRENGTH,
	DEXTERITY,
	INTELLIGENCE,
	MOVEMENT_SPEED,
	MANA_REGENERATION,
	LIFE_REGENERATION,
	LIFE_LEECH,
	MANA_LEECH,
	FIRE_RESISTANCE,
	COLD_RESISTANCE,
	LIGHTNING_RESISTANCE,
	BLOOD_RESISTANCE,
	HOLY_RESISTANCE,
	ENDER_RESISTANCE,
	NATURE_RESISTANCE,
	FIRE_PENETRATION,
	COLD_PENETRATION,
	LIGHTNING_PENETRATION,
	BLOOD_PENETRATION,
	HOLY_PENETRATION,
	ENDER_PENETRATION,
	NATURE_PENETRATION,
	NATURE_DAMAGE,
	AREA_DAMAGE,
	DAMAGE_OVER_TIME,
	IGNITE_DAMAGE,
	BLEED_DAMAGE,
	POISON_DAMAGE,
	IGNITE_CHANCE,
	BLEED_CHANCE,
	POISON_CHANCE,
	AILMENT_DURATION,
	RESOURCE_COST,
	WARD_RECOVERY,
	SUMMON_DAMAGE;

	public String getId() {
		return name().toLowerCase(Locale.ROOT);
	}

	public static Optional<ArpgStat> byId(String id) {
		for (var stat : values()) {
			if (stat.getId().equals(id)) {
				return Optional.of(stat);
			}
		}
		return Optional.empty();
	}
}
